"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from django.core.exceptions import ImproperlyConfigured

# Load environment variables from a .env file in project root when present.
# This keeps API keys and secrets out of source control. For production
# Railway will provide real environment variables via its dashboard.
from dotenv import load_dotenv

# BASE_DIR is used to locate the .env file

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# Go up 3 levels from config/settings.py to reach project root
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Load .env file if present (local development convenience)
# .env is located at project root, not in backend folder
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Read sensitive settings from environment for production deployment (Railway)
SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    # Allow an unsafe fallback for local development only. In production
    # SECRET_KEY must be provided via environment variables.
    if os.getenv('DEBUG', 'True') == 'True':
        SECRET_KEY = 'unsafe-local-dev-key'
    else:
        raise ImproperlyConfigured('Missing SECRET_KEY environment variable')

# When deploying set DEBUG=False in environment. Defaults to True for local dev.
DEBUG = os.getenv('DEBUG', 'True') == 'True'

# ALLOWED_HOSTS can be provided as a comma-separated env var
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '127.0.0.1,localhost').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Local ZENZEE Apps
    'accounts',
    'products',
    'cart',
    'wishlist',
    'orders',
    'reviews',
    'ai',
    'dashboard',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise allows serving static files in production without a separate server
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'backend' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'backend' / 'db.sqlite3',
    }
}

# Optionally configure DATABASES from DATABASE_URL (Railway/Postgres)
DATABASE_URL = os.getenv('DATABASE_URL')
if DATABASE_URL:
    try:
        import dj_database_url
        DATABASES['default'] = dj_database_url.parse(DATABASE_URL, conn_max_age=600)
    except Exception:
        # Minimal fallback parser for postgres-style URLs if dj_database_url isn't installed
        from urllib.parse import urlparse
        url = urlparse(DATABASE_URL)
        if url.scheme.startswith('postgres'):
            DATABASES['default'] = {
                'ENGINE': 'django.db.backends.postgresql_psycopg2',
                'NAME': url.path[1:],
                'USER': url.username,
                'PASSWORD': url.password,
                'HOST': url.hostname,
                'PORT': url.port or '',
            }



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model definition
AUTH_USER_MODEL = 'accounts.User'

# Media Files (User uploads like profile pictures, product images)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'backend' / 'media'

# Additional Static Files directory
STATICFILES_DIRS = [
    BASE_DIR / 'backend' / 'static',
]
STATIC_ROOT = BASE_DIR / 'backend' / 'staticfiles'

